### ISSUE TITLE
Does it support Python3?

### ISSUE THREAD

**Issue by EFFYLYX** [mongodb-labs/py-tpcc#6]

**Comment by v1k1nghawk** [comment]
https://github.com/mongodb-labs/py-tpcc/pull/14

**Comment by utdrmac** [comment]
Any updates on this merge?

```
# python --version
# python tpcc.py mongodb --config pmmdemo_mongo.cfg --warehouses 5 --debug
Traceback (most recent call last):
  File "/root/py-tpcc-master/pytpcc/tpcc.py", line 251, in <module>
    driver.loadConfig(config)
  File "/root/py-tpcc-master/pytpcc/drivers/mongodbdriver.py", line 291, in loadConfig
    userpassword = urllib.quote_plus(user)+':'+urllib.quote_plus(config['passwd'])+"@"
AttributeError: module 'urllib' has no attribute 'quote_plus'
```
